/-
SimilarityOrbits.lean

Hand-derivation (2026-09-23, done before this file, per this corpus's standing
rule: hand-derive first, then Lean, then mark untested until a real kernel run
confirms it -- never the reverse):

A one-parameter subgroup of the similarity group of R^3 is generated by a
scaling rate mu, a rotation rate omega about some axis, and a translation
velocity (perpendicular to / along that axis). Its orbit through a point
solves the affine-linear ODE  dp/dt = mu p + omega x p + u.

Solving that ODE case by case on which of (mu, omega, axial drift) vanish
gives exactly six orbit shapes: line, circle, helix, ray, logarithmic spiral,
and conical spiral/loxodrome (the log spiral is the flat degenerate case of
the conical spiral, not a separate seventh case).

THIS FILE proves ONE case only: mu = 0, omega != 0, axial drift c != 0 --
pure rotation about the z-axis plus constant drift along it. It verifies,
by direct computation of the derivative, that the standard helix
parametrization really is the integral curve of that screw-motion vector
field, i.e. really is what "rotation + constant axial drift" generates.

NOT done here: the other five cases; the converse/uniqueness direction
(that this is the ONLY curve solving the ODE through a given point needs
Mathlib's ODE uniqueness machinery, e.g. Picard-Lindelof -- not attempted);
any claim about which real-world phenomenon (if any) actually has this
symmetry -- that's a separate, later question per file, not this one.

KERNEL RUN 2026-09-26: `lake env lean` against AXLE (Lean v4.14.0, Mathlib v4.14.0):
no errors, no sorry, no warnings. The note below was written before that run and is kept as written.

UNTESTED: no local Lean/Mathlib toolchain in this environment. Every step
was checked by hand against the calculus, not against a compiler. Exact
Mathlib lemma names and argument order (HasDerivAt.comp, .const_mul, .prod,
.const_add) may not match current Mathlib exactly -- that is exactly the
kind of thing `lake env lean` will report precisely, and this file gets
corrected against that real output, not guessed at further from here.
-/

import Mathlib.Analysis.Calculus.Deriv.Basic
import Mathlib.Analysis.Calculus.Deriv.Prod
import Mathlib.Analysis.SpecialFunctions.Trigonometric.Deriv

open Real

/-- The orbit, through the point `(r, 0, z₀)` at time `0`, of the screw
motion with rotation rate `ω` about the z-axis and axial drift rate `c`.
This is the standard circular helix of radius `r`. -/
noncomputable def screwOrbit (r ω c z₀ : ℝ) (t : ℝ) : ℝ × ℝ × ℝ :=
  (r * Real.cos (ω * t), r * Real.sin (ω * t), z₀ + c * t)

/-- The generating vector field of the screw motion: rotate the horizontal
component by 90° at rate `ω`, drift at constant rate `c` along the axis. -/
noncomputable def screwField (ω c : ℝ) (p : ℝ × ℝ × ℝ) : ℝ × ℝ × ℝ :=
  (-ω * p.2.1, ω * p.1, c)

/-- **Main lemma.** The screw orbit is an integral curve of the screw
vector field: its derivative at every time `t` equals the field evaluated
at the orbit's own position. This is the precise, checkable sense in which
"rotation plus constant axial drift generates a helix" -- not an assertion
about the shape, but a statement that this curve solves that ODE. -/
theorem screwOrbit_hasDerivAt (r ω c z₀ t : ℝ) :
    HasDerivAt (screwOrbit r ω c z₀) (screwField ω c (screwOrbit r ω c z₀ t)) t := by
  unfold screwOrbit screwField
  have hx : HasDerivAt (fun t => r * Real.cos (ω * t)) (-(r * ω) * Real.sin (ω * t)) t := by
    have h := ((Real.hasDerivAt_cos (ω * t)).comp t ((hasDerivAt_id t).const_mul ω))
    simpa [mul_comm, mul_assoc, mul_left_comm] using h.const_mul r
  have hy : HasDerivAt (fun t => r * Real.sin (ω * t)) (r * ω * Real.cos (ω * t)) t := by
    have h := ((Real.hasDerivAt_sin (ω * t)).comp t ((hasDerivAt_id t).const_mul ω))
    simpa [mul_comm, mul_assoc, mul_left_comm] using h.const_mul r
  have hz : HasDerivAt (fun t => z₀ + c * t) c t := by
    simpa using ((hasDerivAt_id t).const_mul c).const_add z₀
  -- `HasDerivAt.prod` lives in Deriv.Prod; without that import, dot notation
  -- fell through to `HasFDerivAtFilter.prod` (kernel run 2026-09-23).
  have h := hx.prod (hy.prod hz)
  convert h using 1
  exact Prod.ext (by dsimp only; ring) (Prod.ext (by dsimp only; ring) rfl)
