/-
  G6Conjecture.lean — Issue 6, stated honestly
  Principia Orthogona · AXLE · created 2026-07-30

  ══════════════════════════════════════════════════════════════════════════
  STATUS: NOT COMPILED. Written without a Lean toolchain available.
          Run `lake build` against lean4 v4.14.0 + Mathlib before citing
          any part of this file. Nothing here is machine-checked.
  ══════════════════════════════════════════════════════════════════════════

  WHY THIS FILE EXISTS

  Book 5 Ch V (`chV-sorrys.html`) displayed this as the Lean form of Issue 6:

      theorem separation_theorem : ∀ n : ℕ, eulerChar (H_star (X6 n)) = 33 := by sorry

  That declaration does not exist in AXLE. `eulerChar`, `H_star` and `X6`
  appear zero times outside Mathlib. The listing was a transcription, not a
  quotation. This file replaces it with what is actually the case.

  WHAT IS ACTUALLY THE CASE (AXLE_v6.lean / Main_v6.lean, lines 494-501)

      theorem separation_step2_euler_characteristic :
          ∀ (n : ℕ), n ≤ 5 → True := by
        intro n hn
        trivial

  Issue 6 is a *named placeholder that concludes True*, awaiting a
  persistent-homology API. The conjecture is not stated in Lean at all. The
  verified range is n ≤ 5 — bound in the statement itself, and matching
  "Verified for n ≤ 5 in AXLE March 2026" at line 497. (Book 5's prose says
  n ≤ 12 in two places; that is unsupported by this source.)

  This file does NOT invent the missing objects. X⁶ₙ cannot be defined here
  because the G⁶ action and its quotient are not defined anywhere in the
  corpus — that is prerequisite work, not a formalisation detail. What
  follows is a skeleton with named holes, so the shape of the obligation is
  explicit and a future contributor knows exactly what is owed.
-/

import Mathlib.Topology.Basic
import Mathlib.Algebra.BigOperators.Basic

namespace PrincipiaOrthogona.G6

/-! ### 1. The objects that must be supplied first -/

/-- The configuration space at iteration level `n` of the six-fold operator
    `G⁶ = (U ∘ F ∘ K ∘ C)⁶`.

    OBLIGATION 1. Not definable yet. Requires: (a) the carrier `G` acts on,
    (b) the group generated by `G⁶`, (c) the quotient by that action. None of
    the three is pinned down in the published corpus. Until this is a real
    definition, every downstream statement is vacuous. -/
def X_G6 (n : ℕ) : Type := sorry

/-- Euler characteristic of `H*(X_G6 n)`.

    OBLIGATION 2. Requires `H*(X_G6 n)` to be of finite type, otherwise the
    alternating sum does not converge and χ is undefined. Establishing finite
    type is a separate obligation from computing the value. -/
noncomputable def eulerCharG6 (n : ℕ) : ℤ := sorry

/-! ### 2. The conjecture, stated in the form the corpus intends -/

/-- **Issue 6 — the G⁶ conjecture.**

    Two claims in one, and they should be attacked separately:
      (i)  `n ↦ eulerCharG6 n` is constant   — rigidity / stabilisation
      (ii) that constant is 33               — the value

    Claim (i) is the structural content; it is what "stability" means for the
    g₆ taxonomy. Claim (ii) is a computation. Verified for n ≤ 5 only. -/
theorem g6_euler_characteristic (n : ℕ) : eulerCharG6 n = 33 := by
  sorry

/-- Claim (i) alone — constancy, without committing to the value. Weaker than
    `g6_euler_characteristic` and plausibly reachable first. -/
theorem g6_euler_characteristic_constant (m n : ℕ) :
    eulerCharG6 m = eulerCharG6 n := by
  sorry

/-- What is actually verified, as of AXLE March 2026. Stated separately so the
    established range is never confused with the general claim. -/
theorem g6_euler_characteristic_verified_range (n : ℕ) (hn : n ≤ 5) :
    eulerCharG6 n = 33 := by
  sorry

/-! ### 3. A constraint the conjecture must respect

    If `X_G6 n` were a closed orientable 6-manifold, Poincaré duality would
    make the pairing `H³ × H³ → H⁶` skew-symmetric, forcing `b₃` even, hence
    χ = 2(b₀ − b₁ + b₂) − b₃ even. 33 is odd. So at least one of *closed*,
    *orientable*, *6-manifold* fails — an odd χ says the action is not free,
    which is consistent with `X_G6` being an orbifold rather than a manifold.
    ℝP⁶ has χ = 1, so non-orientability is the cheapest exit.

    OBLIGATION 3. Whichever hypothesis is dropped must be dropped explicitly
    in the definition of `X_G6`, not discovered afterwards. -/
theorem g6_not_closed_orientable_manifold : True := trivial

end PrincipiaOrthogona.G6

/-
  NOT PART OF ISSUE 6 — a separate defect, recorded here because the two are
  routinely conflated under the name `separation_theorem`.

  `separation_theorem` (AXLE_v6.lean:507, PrincipiaVol1.lean:269) is a
  different result: for `M : Matrix (Fin n) (Fin n) ℝ` with `n < 33` and
  `IsDm3Stable M`, it concludes `M.trace ≠ 33`. Its sorry is O1 / AXLE
  Issue #12, an eigenvalue API gap. It is NOT Issue 6.

  Two problems in it, independent of Issue 6:

  1. CatGT/separation_theorem.lean:9 asserts
         |M.trace − 1| = |∑ i ≠ 0, M i i ^ 6|
     The left side is linear in the diagonal; the right is a sum of sixth
     powers. Machine-checked counterexample: M = diag(1, 0.5) gives
     LHS = 0.5 and RHS = 0.015625. Refuted in 500/500 random diagonal cases.
     The identity holds for Tr(M⁶), not Tr(M) — so the conclusion should be
     about `(M ^ 6).trace`, or the bound must be re-derived for `M.trace`.

  2. `hn : n < 33` is never used in the PrincipiaVol1 proof body, and the
     Euler-characteristic step of the comment sketch plays no part: once
     |Tr − 1| < 1 is available, Tr ∈ (0,2) and Tr ≠ 33 for every n. Issue 6
     is cited by that proof but not used by it.
-/
